"""Changed field feedback_like on ResultModel to nullable

Revision ID: 74c2624aff67
Revises: 9b3f99e89a28
Create Date: 2025-11-02 17:55:52.821561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74c2624aff67'
down_revision: Union[str, Sequence[str], None] = '9b3f99e89a28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('result', 'feedback_like',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('result', 'feedback_like',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
